version: "3.3"

networks:
  internal:
    ipam:
      config:
        - subnet: 172.10.0.0/24
services:
  postgresql:
    image: postgres:12.4-alpine
    container_name: pgsql
    ports:
      - 5443:5432
    networks:
      internal:
        ipv4_address: 172.10.0.5
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
